pipeline {
    agent any
    stages {
	   stage('Pull code') {
            steps {
                checkout scm
            }
        }
	stage('Download dependencies') {
            steps {
                dir('frontend') {
                    sh 'yarn'
                }
            }
        }
        stage('Scan & auto fixed code') {
            steps {
                dir('frontend') {
                    sh 'yarn lint'
                }
            }
        }
        stage('Unit Test') {
            steps {
                dir('frontend') {
                    sh 'yarn unit'
                }
            }
        }
		stage('Unit Test Coverage') {
            steps {
                dir('frontend') {
                    sh 'yarn unit:coverage'
                }
            }
        }
        stage('Create Unit Test Report') {
            steps {
                dir('frontend') {
                    publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: false, reportDir: './', reportFiles: 'test-report.html', reportName: 'Unit Test Report', reportTitles: 'Unit Test Report'])
                }
            }
        }
        stage('Create Unit Coverage Report') {
            steps {
                clover(cloverReportDir: 'frontend/coverage', cloverReportFileName: 'clover.xml',
                    healthyTarget: [methodCoverage: 70, conditionalCoverage: 80, statementCoverage: 80],
                    unhealthyTarget: [methodCoverage: 0, conditionalCoverage: 0, statementCoverage: 0],
                    failingTarget: [methodCoverage: 0, conditionalCoverage: 0, statementCoverage: 0]
                )
        }
        stage('Create Unit Test Coverage Report') {
            steps {
                publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: false, reportDir: './frontend/coverage/lcov-report', reportFiles: 'index.html', reportName: 'Unit Test Coverage Report', reportTitles: 'Unit Test Coverage Report'])
            }
        }
        stage('Component Test') {
            steps {
                dir('frontend') {
                    sh "yarn component"
                }
            }
        }
        stage('Component Test Coverage') {
            steps {
                dir('frontend') {
                    sh 'yarn component:coverage'
                }
            }
        }
        stage('Create Component Test Report') {
            steps {
                dir('frontend') {
                    publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: false, reportDir: './', reportFiles: 'test-report.html', reportName: 'Component Test Report', reportTitles: 'Component Test Report'])
                }
            }
        }
        stage('Create Component Test Coverage Report') {
            steps {
                publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: false, reportDir: './frontend/coverage/lcov-report', reportFiles: 'index.html', reportName: 'Component Test Coverage Report', reportTitles: 'Component Test Coverage Report'])
            }
        }
        stage('E2E Test') {
            steps {
                dir('frontend') {
                    sh "yarn e2e"
                }
            }
        }
        stage('Build') {
            steps { 
                dir('frontend') {
                    sh "yarn build"
                }
            }
        }
    }
}